### ISSUE TITLE
Pycharm debugger do not parse the style

### ISSUE THREAD

**Issue by johnMinelli** [xl0/lovely-tensors#11]
Using the `monkey_patch()` with Pycharm the debugger shows the following:

tensor[32, 1, 69] [38;2;127;127;127mall_zeros[0m cuda:0

There is a setting somewhere in the IDE or a parameter to disable the style for tensors repr?

Windows 11
Build PY-222.4345.23

**Comment by xl0** [comment]
Yep, setting `lovely_tensors.repr_str.PRINT_OPTS.color=False` should do the trick, but to be fair, I don't think I've ever tested if it works, and it should be moved to top-level. Please let me know if it works.


TODO
- Move PRINT_OPTS to top level
- Document it
- Add tests

**Comment by johnMinelli** [comment]
Perfect, it works fine

**Comment by xl0** [comment]
Awesome!

I'll keep it open as a reminder to myself to finish the TODO items.

**Comment by xl0** [comment]
@johnMinelli , here's the new version (github, not yet in pip)

https://xl0.github.io/lovely-tensors/03_utils.config.html
