### ISSUE TITLE
ImportError: cannot import name 'PRINT_OPTS' 

### ISSUE THREAD

**Issue by Sandv** [xl0/lovely-tensors#12]
Would *love* to use this package!

But alas, I get this error below on import. Installed with pip. Any advice would be greatly appreciated. Thank you for your package!

`Traceback (most recent call last):

  File "/home/v/efficient/segment/segment.py", line 29, in <module>
    import lovely_tensors as lt

  File "/home/v/miniconda3/envs/pt/lib/python3.9/site-packages/lovely_tensors/__init__.py", line 3, in <module>
    from lovely_tensors.repr_str import *

  File "/home/v/miniconda3/envs/pt/lib/python3.9/site-packages/lovely_tensors/repr_str.py", line 11, in <module>
    from lovely_numpy.utils import np_to_str_common, pretty_str, sparse_join, plain_repr, PRINT_OPTS

ImportError: cannot import name 'PRINT_OPTS' from 'lovely_numpy.utils' (/home/v/miniconda3/envs/pt/lib/python3.9/site-packages/lovely_numpy/utils/__init__.py)`

`
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
absl-py                   1.2.0                    pypi_0    pypi
aiohttp                   3.8.3                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
albumentations            1.3.0                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
argon2-cffi               20.1.0           py39h3811e60_2    conda-forge
ascii-graph               1.5.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blessed                   1.19.1                   pypi_0    pypi
bpytop                    1.0.68                   pypi_0    pypi
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.5.30            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2021.5.30        py39hf3d152e_0    conda-forge
cffi                      1.14.6           py39he32792d_0    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.1                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
configparser              5.0.2                    pypi_0    pypi
cryptography              3.4.7            py39hbca0aa6_0    conda-forge
cudatoolkit               10.2.89              hfd86e86_1  
cursor                    1.3.5                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
debugpy                   1.4.1            py39he80948d_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docker-pycreds            0.4.0                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
einops                    0.3.2                    pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
fastapi                   0.85.1                   pypi_0    pypi
fastcore                  1.5.27                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.8.0                    pypi_0    pypi
fpzip                     1.2.0                    pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0  
frozenlist                1.3.1                    pypi_0    pypi
fsspec                    2022.8.2                 pypi_0    pypi
gitdb                     4.0.7                    pypi_0    pypi
gitpython                 3.1.18                   pypi_0    pypi
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.12.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
gpustat                   1.1.0.dev0               pypi_0    pypi
grpcio                    1.49.1                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
huggingface-hub           0.11.0                   pypi_0    pypi
idna                      3.1                pyhd3deb0d_0    conda-forge
imageio                   2.22.1                   pypi_0    pypi
importlib-metadata        4.8.1            py39hf3d152e_0    conda-forge
intel-openmp              2021.3.0          h06a4308_3350  
ipdb                      0.13.9                   pypi_0    pypi
ipykernel                 6.3.1            py39hef51801_0    conda-forge
ipython                   7.27.0           py39hef51801_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5                    pypi_0    pypi
jedi                      0.18.0           py39hf3d152e_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            7.0.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39hf3d152e_0    conda-forge
jupyter_server            1.10.2             pyhd8ed1ab_0    conda-forge
jupyterlab                3.1.10             pyhd8ed1ab_0    conda-forge
jupyterlab-widgets        1.0.2                    pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.7.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.2                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libwebp-base              1.2.0                h27cfd23_0  
line-profiler             3.5.1                    pypi_0    pypi
lovely-numpy              0.2.0                    pypi_0    pypi
lovely-tensors            0.1.8                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mistune                   0.8.4           py39h3811e60_1004    conda-forge
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.0            py39h42c9631_2  
mkl_random                1.2.2            py39h51133e4_0  
monai                     1.0.1                    pypi_0    pypi
monai-weekly              0.7.dev2136              pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
nbclassic                 0.3.1              pyhd8ed1ab_1    conda-forge
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py39hf3d152e_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
netmon                    0.2.0                    pypi_0    pypi
nettle                    3.7.3                hbbd107a_1  
networkx                  2.8.8                    pypi_0    pypi
nibabel                   3.2.1                    pypi_0    pypi
ninja                     1.10.2               hff7bd54_1  
notebook                  6.4.3              pyha770c72_0    conda-forge
numpngw                   0.1.2                    pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
nvidia-htop               1.0.5                    pypi_0    pypi
nvidia-ml-py              11.495.46                pypi_0    pypi
oauthlib                  3.2.1                    pypi_0    pypi
olefile                   0.46                       py_0  
opencv-python-headless    4.6.0.66                 pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.1                    pypi_0    pypi
pandoc                    2.14.2               h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0                    pypi_0    pypi
pip                       21.2.4           py37h06a4308_0  
pipreqs                   0.4.11                   pypi_0    pypi
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.20             pyha770c72_0    conda-forge
protobuf                  3.17.3                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydantic                  1.10.2                   pypi_0    pypi
pydeprecate               0.3.2                    pypi_0    pypi
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyinstrument              4.3.0                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypng                     0.20220715.0             pypi_0    pypi
pyrsistent                0.17.3           py39h3811e60_2    conda-forge
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.6                h12debd9_1  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.9.0           py3.9_cuda10.2_cudnn7.6.5_0    pytorch
pytorch-lightning         1.7.7                    pypi_0    pypi
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzfp                     0.5.5                    pypi_0    pypi
pyzmq                     19.0.2           py39hb69f2a1_2    conda-forge
qudida                    0.0.4                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
requests-unixsocket       0.2.0                      py_0    conda-forge
rsa                       4.9                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.3                    pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
sentry-sdk                1.3.1                    pypi_0    pypi
setuptools                52.0.0           py39h06a4308_0  
shortuuid                 1.0.1                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0  
sklearn                   0.0                      pypi_0    pypi
smmap                     4.0.0                    pypi_0    pypi
sniffio                   1.2.0            py39hf3d152e_1    conda-forge
sqlite                    3.36.0               hc218d9a_0  
starlette                 0.20.4                   pypi_0    pypi
subprocess32              3.5.4                    pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 2.0.1                    pypi_0    pypi
terminado                 0.11.1           py39hf3d152e_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.10.10               pypi_0    pypi
timm                      0.6.11                   pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                   pypi_0    pypi
torch-tb-profiler         0.4.0                    pypi_0    pypi
torchaudio                0.9.0                      py39    pytorch
torchmetrics              0.10.0                   pypi_0    pypi
torchsummary              1.5.1                    pypi_0    pypi
torchvision               0.10.0               py39_cu102    pytorch
tornado                   6.1              py39h3811e60_1    conda-forge
tqdm                      4.62.2                   pypi_0    pypi
traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2021a                h5d7bf9c_0  
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
uvicorn                   0.19.0                   pypi_0    pypi
vulture                   2.6                      pypi_0    pypi
wandb                     0.12.1                   pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          0.57.0           py39hf3d152e_4    conda-forge
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
xgboost                   1.7.1                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yarg                      0.1.9                    pypi_0    pypi
yarl                      1.8.1                    pypi_0    pypi
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zfpy                      1.0.0.post3              pypi_0    pypi
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  

`

**Comment by Maccy-Z** [comment]
Downgrading to 0.1.5 fixed for me. 
It was working fine yesterday, this error appeared today. Seems a recent change broke something.

**Comment by xl0** [comment]
Hi. Sorry, my bad!

Please downgrade `lovely-numpy` to `0.1.3`. Yes `-numpy`. I will fix it in 2 hours.

**Comment by xl0** [comment]
I've pushed out `lovely-tensors` 0.1.9. Did it fix the issue for you? Don't downgrade `lovely-numpy`.

**Comment by Sandv** [comment]
It works!
Thank you so much for your superfast help!
Veit
