### ISSUE TITLE
How to save the statistics img ?

### ISSUE THREAD

**Issue by zxczrx123** [xl0/lovely-tensors#15]
Hi, thanks for your great work!

I want to know how to save the img result of plt() ? Is there a simple function to call ?

**Comment by xl0** [comment]
Hmm, there is no clean way to do so at the moment.

I'm working on changing the interaction between matplotlib and Lovely at the moment, hang on tight. :)

As a workaround:
```py
fig = lt.repr_plt._plot(numbers)
fig.savefig("plot.png", dpi=200)
```

**Comment by xl0** [comment]
I'll keep it open until proper fix.

**Comment by xl0** [comment]
@zxczrx123 , there is a proper way now:
https://xl0.github.io/lovely-tensors/matplotlib.html

**Comment by zxczrx123** [comment]
Great, just what I needed!
