### ISSUE TITLE
Receive an Import Error using this libraries on a notebook

### ISSUE THREAD

**Issue by Rami-Ismael** [xl0/lovely-tensors#19]
ImportError: cannot import name 'cached_property' from 'functools'
This is error I receive. I am using python 3.7.13 on a local PC on a notebook.

The error is causing the cache_properties was introduced in python 3.8.

**Comment by xl0** [comment]
Thank you for the report. I'll fix it today.

**Comment by xl0** [comment]
@Rami-Ismael , I fixed the issue. Could you please confirm that the current git works for you?

```
pip install git+https://github.com/xl0/lovely-tensors
```

**Comment by Rami-Ismael** [comment]
Thank you so much. It looks like it was expected. Furthermore, thank you so much for making a great library. I first heard about it in the Yannic Kilcher discord. I have always wanted to use libraries for a project.   I want to express gratitude for fixing my issues

**Comment by xl0** [comment]
:two_hearts:
