### ISSUE TITLE
Support for numpy

### ISSUE THREAD

**Issue by idow09** [xl0/lovely-tensors#2]
Hi! Any plan to support `numpy.ndarray`s?
Will you accept a PR?
Thanks!

**Comment by xl0** [comment]
Hi!

I'm working on [https://github.com/xl0/lovely-jax][Lovely JAX], which is almost NumPy, so it's not a problem to add a lovely-np as well.

My concern with NumPy is, what kind of summary and visualizations do we show?
PyTorch and to a large extent JAX are used for NNs, so I have a rough idea of what should go into the summary. But I'm not sure how people use NumPy, and what would make sense for them.

Do you use NumPy a lot? What's the use case, and what kind of summary would make sense for you?

I can also add lovely-np that mimics lovely-tensors, and see if people will come up with better ways to summarize ndarrays.

**Comment by idow09** [comment]
Thanks, excellent answer!
In fact, I'm using `numpy` for ML applications too. Many times there are manipulations that are performed on the arrays before I transform them into tensors, simply because the ecosystem has some libraries/features that are built around `numpy` (e.g. `python-opencv`, `Pillow`, etc.). It is simply how things are.
Anyway, I have to admit that above all, the feature I loved most about `lovely-tensors` is its most basic form of summary: printing the very basic stats like range, mean, std. And those are relevant IMO no matter what purpose your arrays have.
Of course, more sophisticated visualizations can be available too as it's up to the user to decide to use them.

By the way, why do you separate those packages? Wouldn't it be nicer to have support for all types in one package?
Anyway thanks so much for your work.

**Comment by xl0** [comment]
Cool, I'll do the same summary then.

I'm not 100% sure which approach would be better - split or keep together. In the end, I can't share that much code between PyTorch and JAX, and I'd rather avoid building an abstraction layer, and I'd have to pick the backend dynamically and detect module availability dynamically because I can't have dependencies on both.

I feel this library would be better off being as simple as possible - If there is some weird bug that you can't explain, `lovely-tensors` would probably be the first suspect because it sits between you and your data. It's code that I expect to be looked at, and it might already be a bit on the harder side with the proxy classes.

Now, NumPy and JAX are quite similar (except arrays are immutable in JAX, and some of the array indexing does not work) and have a smooth interface, so it probably makes sense to handle them together. I'll see what feels more natural. Maybe it makes sense to re-write much of `lovely-tensors` in NumPy, and have the other libraries as thin wrappers on top.

**Comment by idow09** [comment]
It sounds very reasonable to me. Please let me know if I can be of help! And good luck with this awesome effort 💪 . It is already one of my favorite libraries.

**Comment by xl0** [comment]
Hi! Excellent timing, I just pushed the first bits of lovely-numpy:  https://github.com/xl0/lovely-numpy :)

Are you familiar with nbdev?

**Comment by xl0** [comment]
The last problem I had - NumPy's main class np.ndarray is written in C, and you can't monkey-patch it the way I do with torch.Tensor.

I think this is the solution: https://stackoverflow.com/questions/53313496/a-more-compact-repr-for-my-numpy-array
But it's getting late where I am, and it's near bedtime. Would you like to give it a try?

For nbdev and why it's awesome: https://www.youtube.com/watch?v=67FdzLSt4a .
You need to run nbdev_prepare to clean up notebooks and run tests and nbdev_preview to preview the generated docs.

**Comment by xl0** [comment]
> It is already one of my favorite libraries.

:heart:

**Comment by idow09** [comment]
Sure I'll definitely try! I know `nbdev` but it is my first time actually using it.

**Comment by idow09** [comment]
OK done. Please see [PR](https://github.com/xl0/lovely-numpy/pull/1).

**Comment by xl0** [comment]
Thank you! It looks good; I'll try and merge it this afternoon!

I have the image-related stuff mostly ported to NumPy, but I have not touched .plt yet. Would you like to give it a go?

The architecture I have in mind: A plot( ) that accepts a NumPy array for the data and a string for the caption. Then the platform-specific part would be a thin wrapper that gets the data summary string (which has platform-specific bits), converts the data to NumPy, and passes both to the generic plot. But that's just my thoughts.

**Comment by idow09** [comment]
Where do you have it? I didn't see image related code in the repo. Anyway I'd really love implementing those too, but take into account that I'll be available only on Sunday, unfortunately.
And also, I'm not sure I fully understand what you've just described. Wanna give some example?
Lastly we can move the discussion to a dedicated issue in the numpy repo itself, will make more sense to future readers.
Thanks!

**Comment by idow09** [comment]
And just to make sure: we won't be able to use the nicer `.plt`, only an explicit function call. For the same reason we couldn't really patch the `__repr__`

**Comment by xl0** [comment]
Sent you an email.

**Comment by xl0** [comment]
And thank you for the PR, it's been merged. :)
:+1:

**Comment by xl0** [comment]
https://github.com/xl0/lovely-numpy
