### ISSUE TITLE
Can you fine tune the view in any way?

### ISSUE THREAD

**Issue by Meehai** [xl0/lovely-tensors#22]
For example, is there any way to disable showing if there are NaNs, or to simply show just the shape?

Perhaps set_config() could accept a callback that receives a tensor and outputs a string (and defaults to current implementation), so we can fine tune it further based on custom logic?

**Comment by xl0** [comment]
Heya. I'm not against it, but this would definitely require a bit of effort because this functionality is split and semi-duplicated between lovely-numpy and tensors/jax/etc. I don't think I'd have time for it, but I would be open to a PR, although, as I said, it's not a trivial change.
