### ISSUE TITLE
Add support to Named Tensors

### ISSUE THREAD

**Issue by fredguth** [xl0/lovely-tensors#23]
There is a [new feature in PyTorch](https://pytorch.org/docs/stable/named_tensor.html) for naming the dimensions of a tensor.

Running lovely_tensors in Jupyter I get this:

```
import torch
import lovely_tensors as lt 
lt.__version__, torch.__version__

>> ('0.1.15', '2.3.1+cu121')

t = torch.zeros(2, 3, names=('N', 'C'))
t

>> tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('N', 'C'))

lt.monkey_patch()
t

>>
RuntimeError: aten::amin is not yet supported with named tensors. Please drop names via `tensor = tensor.rename(None)`, call the op with an unnamed tensor, and set names on the result of the operation.

```

**Comment by xl0** [comment]
Thank you for bringing this to my attention. Yes, should be fixed. I'll try to do it this week. I need to confirm that tensor.rename does not allocate extra memory

**Comment by xl0** [comment]
@fredguth how do you feel it should look like?
```
torch.zeros(2, 3, 4, names=('N', 'C', None))
```
`tensor[2, 3, 4]  names=('N', 'C') n=24 all_zeros`
`tensor[2, 3, 4, names=('N', 'C')] n=24 all_zeros`
`tensor[N=2, C=3, 4] n=24 all_zeros`

**Comment by xl0** [comment]
Looking at them side by side, I think the last one is a clear winner. :)

**Comment by xl0** [comment]
Done, and I've pushed out a new release 0.2.16. In pip now, in conda in a few hours.
