### ISSUE TITLE
Meta devices are not supported

### ISSUE THREAD

**Issue by lukemelas** [xl0/lovely-tensors#25]
Thanks for the nice library.

Printing tensors on meta devices leads to an error:
```python
import torch
import lovely_tensors
lovely_tensors.monkey_patch()
print(torch.randn(1, 10, device="cpu"))  # works
print(torch.randn(1, 10, device="meta"))  # fails
```
The error is
```
NotImplementedError: Cannot copy out of meta tensor; no data!
```
An easy fix is to change [this line](https://github.com/xl0/lovely-tensors/blob/5d15bee6787f743ebff100fe1b4b8dfe835307b3/lovely_tensors/repr_str.py#L106C5-L106C27):
```diff
-    if plain or is_fake(t):
+    if plain or is_fake(t) or t.device.type == "meta":
```
Then everything works as desired.

**Comment by xl0** [comment]
Thank you, I'll have a look soon!

**Comment by lukemelas** [comment]
Awesome, thanks!

**Comment by xl0** [comment]
Done
![image](https://github.com/user-attachments/assets/a34e422f-1dae-48d1-8f32-560bda1a5b26)

new version in pip, conda should pick it up within a day.

**Comment by lukemelas** [comment]
Brilliant, thanks!
