### ISSUE TITLE
Does not install to active virtual environment (venv) but to .local instead 

### ISSUE THREAD

**Issue by jackokring** [xl0/lovely-tensors#7]
WARNING: The scripts f2py, f2py3 and f2py3.9 are installed in '/home/jackokring/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/home/jackokring/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/home/jackokring/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts ipython and ipython3 are installed in '/home/jackokring/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts convert-caffe2-to-onnx, convert-onnx-to-caffe2 and torchrun are installed in '/home/jackokring/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by xl0** [comment]
Hi.

Could you please elaborate on your environment and steps needed to reproduce?
I don't normally use vevns, but conda instead.

After deactivating conda, I ran
```
$ python -m venv test-venv
$ ./test-venv/bin/activate
(test-venv)$ pip install lovely-tensors
```

Which seems to have worked just fine.

**Comment by jackokring** [comment]
`(venv) jackokring@penguin:~/www$ pip install lovely-tensors` with the venv activation in `.bashrc`. Chromebook linux. `which python` is `/home/jackokring/www/venv/bin/python` and `python-is-python3` installed. `which pip` is `/home/jackokring/www/venv/bin/pip` and a symbolic link to `/home/jackokring/www/venv/bin/pip3`.

**Comment by jackokring** [comment]
I had a really messed up venv. Problem fixed.
